### ISSUE TITLE
broken icons

### ISSUE THREAD

**Issue by judehansen** [jzsfkzm/color-icons-for-gmail#3]
Hi. The icons don't seem to work anymore. I think gmail changed the shape of the sprite. Thanks for the extension, love the icons!

![general_black-561d1748a305c61c6fe250344ec8165c](https://f.cloud.github.com/assets/780298/102569/ceeff850-692d-11e2-8f85-e9642a3ece3f.png)

**Comment by Fyrebaugh** [comment]
I am getting the same issue on one computer, this one, just gets the monochrome icons, my laptop the icons are grey but they change, instead of the delete trashcan, I get the paperclip when this extension is installed.

**Comment by judehansen** [comment]
fixed! nice. thanks jzsfkzm!

**Comment by jzsfkzm** [comment]
For a recap: Google changed the shape of the spite, it has at least two different versions live, plus they still use the old one too. It's kinda weird to say the least.
Here's the old one:
https://ssl.gstatic.com/ui/v1/icons/mail/sprite_black2.png
These are also in use:
https://ssl.gstatic.com/mail/sprites/general_black-4e49329d8cd04bc422ea84b27726c412.png
https://ssl.gstatic.com/mail/sprites/general-b973babf974131150c61588b4f3beb46.png

These sprites having an md5 in their name make me think they are generated in some way. Anyway, thank you for your report, I found a way hacking through that.

**Comment by Fyrebaugh** [comment]
Thanks very much, I feel the colors help a lot.  I actually preferred the
original Gmail look before Google updated it to the new, but the newer
interface with the less white space needs something.  If we have to go with
the icons instead of the text links this is much better!

Sincerely,

Matt Wyckoff

On Wed, Feb 6, 2013 at 5:04 AM, Jozsef Kozma notifications@github.comwrote:

> For a recap: Google changed the shape of the spite, it has at least
> different versions live, plus they still use the old one too. It's kinda
> weird to say the least.
> Here's the old one:
> https://ssl.gstatic.com/ui/v1/icons/mail/sprite_black2.png
> These are also in use:
> 
> https://ssl.gstatic.com/mail/sprites/general_black-4e49329d8cd04bc422ea84b27726c412.png
> 
> https://ssl.gstatic.com/mail/sprites/general-b973babf974131150c61588b4f3beb46.png
> 
> These sprites having an md5 in their name make me think they are generated
> in some way. Anyway, thank you for your report, I found a way hacking
> through that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jzsfkzm/color-icons-for-gmail/issues/3#issuecomment-13176815.

## 

••••••••••••••••••••••
Matt Wyckoff
Don't ping my cheese with your bandwidth
Dilbert 8/10/06
•••••••••••••••••••••••
